export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';
export const FETCH_DETAIL_PRODUCT = 'FETCH_DETAIL_PRODUCT';
export const FETCH_DETAIL_PRODUCT_SUCCESS = 'FETCH_DETAIL_PRODUCT_SUCCESS';
export const FETCH_DETAIL_PRODUCT_FAILED = 'FETCH_DETAIL_PRODUCT_FAILED';

export const FETCH_PRODUCT_CATEGORY = 'FETCH_PRODUCT_CATEGORY';
export const FETCH_PRODUCT_CATEGORY_SUCCESS = 'FETCH_PRODUCT_CATEGORY_SUCCESS';

export const FETCH_PRODUCT_SEARCH = 'FETCH_PRODUCT_SEARCH';
export const FETCH_PRODUCT_SEARCH_SUCCESS = 'FETCH_PRODUCT_SEARCH_SUCCESS';

